services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: gym
      MONGO_INITDB_ROOT_PASSWORD: gym

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gym
      ME_CONFIG_MONGODB_ADMINPASSWORD: gym
      ME_CONFIG_MONGODB_URL: mongodb://gym:gym@mongo:27017/
      ME_CONFIG_BASICAUTH: false