// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type AdminUser struct {
	ID        int32
	CreatedAt time.Time
	Username  string
	Email     string
	Password  string
}

type User struct {
	ID        int32
	CreatedAt time.Time
	Enabled   sql.NullBool
	Username  string
	Email     string
	Password  string
}
