// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rfids.sql

package sqlc

import (
	"context"
)

const getUserIdByRfidId = `-- name: GetUserIdByRfidId :one
SELECT id
FROM users
WHERE rfid = $1
`

func (q *Queries) GetUserIdByRfidId(ctx context.Context, rfid string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIdByRfidId, rfid)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateUserRfid = `-- name: UpdateUserRfid :exec
UPDATE users
  set rfid = $2
WHERE id = $1
`

type UpdateUserRfidParams struct {
	ID   int32
	Rfid string
}

func (q *Queries) UpdateUserRfid(ctx context.Context, arg UpdateUserRfidParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRfid, arg.ID, arg.Rfid)
	return err
}
