services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - 5432:5432

  backend:
    build: .
    env_file: .env
    restart: always
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: ${DATABASE_URL}

  migrate:
    image: golang:1.23-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["go", "run", "internal/postgres/migrate.go"]
    depends_on:
      - postgres