definitions:
  exercise.ExerciseData:
    properties:
      finished_at:
        type: integer
      started_at:
        type: integer
      weight:
        type: integer
    required:
    - finished_at
    - started_at
    - weight
    type: object
  exercise.ExerciseRecord:
    properties:
      data:
        items:
          $ref: '#/definitions/exercise.ExerciseData'
        type: array
      origin_id:
        type: string
      user_id:
        type: string
    required:
    - data
    - origin_id
    - user_id
    type: object
info:
  contact: {}
paths:
  /exercises:
    post:
      consumes:
      - application/json
      parameters:
      - description: Exercises
        in: body
        name: exercises
        required: true
        schema:
          items:
            $ref: '#/definitions/exercise.ExerciseRecord'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Create a couple of exercises
      tags:
      - exercises
  /users/{user_id}/origins/{origin_id}/exercises:
    get:
      consumes:
      - application/json
      parameters:
      - description: Start time in Unix timestamp
        in: query
        name: started_at
        required: true
        type: integer
      - description: Finish time in Unix timestamp
        in: query
        name: finished_at
        required: true
        type: integer
      - description: Origin ID
        in: path
        name: origin_id
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Get exercises based on query parameters
      tags:
      - exercises
swagger: "2.0"
