services:
#  mosquitto:
#    image: eclipse-mosquitto
#    hostname: mosquitto
#    container_name: mosquitto
#    restart: unless-stopped
#    ports:
#      - "${MQTT_PORT}:${MQTT_PORT}"
#    volumes:
#      - ./mosquitto:/mosquitto
#    networks:
#      - smart_gym_network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - smart_gym_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8083:8083"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - smart_gym_network

  workout-logs:
    build:
      context: ../workout-logs
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
#      - mosquitto
      - mongo
      - mongo-express
    ports:
      - "3030:3030"
    environment:
      MOSQUITTO_DOMAIN: ${MOSQUITTO_DOMAIN}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_CLEAN_SESSION: ${MQTT_CLEAN_SESSION}
      MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017
    restart: unless-stopped
    networks:
      - smart_gym_network

networks:
  smart_gym_network:
