services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      - smart_gym_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1883"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - smart_gym_network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - smart_gym_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - smart_gym_network

  core-service:
    restart: always
    env_file: .env
    build:
      context: ../core-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - smart_gym_network
    depends_on:
      core-service-migrate:
        condition: service_completed_successfully
      postgres:
          condition: service_healthy


  core-service-migrate:
    image: golang:1.23-alpine
    volumes:
      - ../core-service:/app
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: [ "go", "run", "internal/postgres/migrate.go" ]
    networks:
      - smart_gym_network
    depends_on:
      postgres:
        condition: service_healthy

  workout-logs:
    restart: unless-stopped
    env_file: .env
    build:
      context: ../workout-logs
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      MOSQUITTO_DOMAIN: ${MOSQUITTO_DOMAIN}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_CLEAN_SESSION: ${MQTT_CLEAN_SESSION}
      MQTT_TOPIC_PREFIX: ${MQTT_TOPIC_PREFIX}
      MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017
    networks:
      - smart_gym_network
    depends_on:
      mosquitto:
        condition: service_healthy

networks:
  smart_gym_network:
