// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/01/2025, 16:13:53
const configMerger = require("/home/talison/projects/go/smart-gym/frontnuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/talison/projects/go/smart-gym/frontnuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/plugins/**/*.{js,ts,mjs}","/home/talison/projects/go/smart-gym/frontnuxt/composables/**/*.{js,ts,mjs}","/home/talison/projects/go/smart-gym/frontnuxt/utils/**/*.{js,ts,mjs}","/home/talison/projects/go/smart-gym/frontnuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/talison/projects/go/smart-gym/frontnuxt/app.config.{js,ts,mjs}"] } }));

module.exports = config
